import AndroidSwipeRefreshLayoutNativeComponent from "react-native/Libraries/Components/RefreshControl/AndroidSwipeRefreshLayoutNativeComponent"

class Constants {
    static ESTABLISHMENT_TYPE = [
        "Agriculture",
        "Bank",
        "Barangay Hall",
        "Checkpoint",
        "Church",
        "City Hall",
        "City Heath Office",
        "Clinic",
        "Convenience Store",
        "Deparment Store",
        "Gas Station",
        "Government Office",
        "Hardware",
        "Hospital",
        "Hotel",
        "Insurance",
        "Laboratory",
        "Mall",
        "Market",
        "Military Installation",
        "Pharmacy/Drugstore",
        "Police Station",
        "Public Vehicle",
        "Remittance Center",
        "Restaurant",
        "Roving Team",
        "School",
        "Store",
        "Supermarket",
        "Others"
    ]
    static ESTABLISHMENT_BARANGAY = [
        "Acacia",
        "Agdao",
        "Alambre",
        "Alejandra Navarro (Lasang)",
        "Alfonso Angliongto Sr.",
        "Angalan",
        "Atan-Awe",
        "Baganihan",
        "Bago Aplaya",
        "Bago Gallera",
        "Bago Oshiro",
        "Baguio (Pob.)",
        "Balengaeng",
        "Baliok",
        "Bangkas Heights",
        "Bantol",
        "Baracatan",
        "Barangay 10-A (Pob.)",
        "Barangay 11-B (Pob.)",
        "Barangay 12-B (Pob.)",
        "Barangay 13-B (Pob.)",
        "Barangay 14-B (Pob.)",
        "Barangay 15-B (Pob.)",
        "Barangay 16-B (Pob.)",
        "Barangay 17-B (Pob.)",
        "Barangay 18-B (Pob.)",
        "Barangay 19-B (Pob.)",
        "Barangay 1-A (Pob.)",
        "Barangay 20-B (Pob.)",
        "Barangay 21-C (Pob.)",
        "Barangay 22-C (Pob.)",
        "Barangay 23-C (Pob.)",
        "Barangay 24-C (Pob.)",
        "Barangay 25-C (Pob.)",
        "Barangay 26-C (Pob.)",
        "Barangay 27-C (Pob.)",
        "Barangay 28-C (Pob.)",
        "Barangay 29-C (Pob.)",
        "Barangay 2-A (Pob.)",
        "Barangay 30-C (Pob.)",
        "Barangay 31-D (Pob.)",
        "Barangay 32-D (Pob.)",
        "Barangay 33-D (Pob.)",
        "Barangay 34-D (Pob.)",
        "Barangay 35-D (Pob.)",
        "Barangay 36-D (Pob.)",
        "Barangay 37-D (Pob.)",
        "Barangay 38-D (Pob.)",
        "Barangay 39-D (Pob.)",
        "Barangay 3-A (Pob.)",
        "Barangay 40-D (Pob.)",
        "Barangay 4-A (Pob.)",
        "Barangay 5-A (Pob.)",
        "Barangay 6-A (Pob.)",
        "Barangay 7-A (Pob.)",
        "Barangay 8-A (Pob.)",
        "Barangay 9-A (Pob.)",
        "Bato",
        "Bayabas",
        "Biao Escuela",
        "Biao Guianga",
        "Biao Joaquin",
        "Binugao",
        "Bucana",
        "Buda",
        "Buhangin (Pob.)",
        "Bunawan (Pob.)",
        "Cabantian",
        "Cadalian",
        "Calinan (Pob.)",
        "Callawa",
        "Camansi",
        "Carmen",
        "Catalunan Grande",
        "Catalunan Pequeño",
        "Catigan",
        "Cawayan",
        "Centro (San Juan)",
        "Colosas",
        "Communal",
        "Crossing Bayabas",
        "Dacudao",
        "Dalag",
        "Dalagdag",
        "Daliao",
        "Daliaon Plantation",
        "Datu Salumay",
        "Dominga",
        "Dumoy",
        "Eden",
        "Fatima (Benowang)",
        "Gatungan",
        "Gov. Paciano Bangoy",
        "Gov. Vicente Duterte",
        "Gumalang",
        "Gumitan",
        "Ilang",
        "Inayangan",
        "Indangan",
        "Kap. Tomas Monteverde, Sr.",
        "Kilate",
        "Lacson",
        "Lamanan",
        "Lampianao",
        "Langub",
        "Lapu-lapu",
        "Leon Garcia, Sr.",
        "Lizada",
        "Los Amigos",
        "Lubogan",
        "Lumiad",
        "Ma-a",
        "Mabuhay",
        "Magsaysay",
        "Magtuod",
        "Mahayag",
        "Malabog",
        "Malagos",
        "Malamba",
        "Manambulan",
        "Mandug",
        "Manuel Guianga",
        "Mapula",
        "Marapangi",
        "Marilog",
        "Matina Aplaya",
        "Matina Biao",
        "Matina Crossing",
        "Matina Pangi",
        "Megkawayan",
        "Mintal",
        "Mudiang",
        "Mulig",
        "New Carmen",
        "New Valencia",
        "Pampanga",
        "Panacan",
        "Panalum",
        "Pandaitan",
        "Pangyan",
        "Paquibato (Pob.)",
        "Paradise Embak",
        "Rafael Castillo",
        "Riverside",
        "Salapawan",
        "Salaysay",
        "Saloy",
        "San Antonio",
        "San Isidro (Licanan)",
        "Santo Niño",
        "Sasa",
        "Sibulan",
        "Sirawan",
        "Sirib",
        "Suawan (Tuli)",
        "Subasta",
        "Sumimao",
        "Tacunan",
        "Tagakpan",
        "Tagluno",
        "Tagurano",
        "Talandang",
        "Talomo (Pob.)",
        "Talomo River",
        "Tamayong",
        "Tambobong",
        "Tamugan",
        "Tapak",
        "Tawan-tawan",
        "Tibuloy",
        "Tibungco",
        "Tigatto",
        "Toril (Pob.)",
        "Tugbok (Pob.)",
        "Tungakalan",
        "Ubalde",
        "Ula",
        "Vicente Hizon Sr.",
        "Waan",
        "Wangan",
        "Wilfredo Aquino",
        "Wines"
    ]

    static GENDER = [
        "Male",
        "Female"
    ]

    static DOB_MONTH = [
        "JANUARY",
        "FEBRUARY",
        "MARCH",
        "APRIL",
        "MAY",
        "JUNE",
        "JULY",
        "AUGUST",
        "SEPTEMBER",
        "OCTOBER",
        "NOVEMBER",
        "DECEMBER"
    ]
    static DOB_DAY = [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31"

    ]
    static DOB_YEAR = [
        "2022",
        "2021",
        "2020",
        "2019",
        "2018",
        "2017",
        "2016",
        "2015",
        "2014",
        "2013",
        "2012",
        "2011",
        "2010",
        "2009",
        "2008",
        "2007",
        "2006",
        "2005",
        "2004",
        "2003",
        "2002",
        "2001",
        "2000",
        "1999",
        "1998",
        "1997",
        "1996",
        "1995",
        "1994",
        "1993",
        "1992",
        "1991",
        "1990",
        "1989",
        "1988",
        "1987",
        "1986",
        "1985",
        "1984",
        "1983",
        "1982",
        "1981",
        "1980",
        "1979",
        "1978",
        "1977",
        "1976",
        "1975",
        "1974",
        "1973",
        "1972",
        "1971",
        "1970",
        "1969",
        "1968",
        "1967",
        "1966",
        "1965",
        "1964",
        "1963",
        "1962",
        "1961",
        "1960",
        "1959",
        "1958",
        "1957",
        "1956",
        "1955",
        "1954",
        "1953",
        "1952",
        "1951",
        "1950",
        "1949",
        "1948",
        "1947",
        "1946",
        "1945",
        "1944",
        "1943",
        "1942",
        "1941",
        "1940",
        "1939",
        "1938",
        "1937",
        "1936",
        "1935",
        "1934",
        "1933",
        "1932",
        "1931",
        "1930",
        "1929",
        "1928",
        "1927",
        "1926",
        "1925",
        "1924",
        "1923",
        "1922",
        "1921",
        "1920",
        "1919",
        "1918",
        "1917",
        "1916",
        "1915",
        "1914",
        "1913",
        "1912",
        "1911",
        "1910",
        "1909",
        "1908",
        "1907",
        "1906",
        "1905",
        "1904",
        "1903",
        "1902",
        "1901",
        "1900"
    ]

}


export default Constants